packages:
  - apps/*
  - packages/*

catalog:
  dayjs: ^1.11.18
  embla-carousel-react: ^8.6.0
  recharts: ^3.2.1
  '@tabler/icons-react': ^3.35.0

catalogs:
  mantine:
    '@mantine/carousel': ^8.3.4
    '@mantine/charts': ^8.3.4
    '@mantine/code-highlight': ^8.3.4
    '@mantine/core': ^8.3.4
    '@mantine/dates': ^8.3.4
    '@mantine/dropzone': ^8.3.4
    '@mantine/form': ^8.3.4
    '@mantine/hooks': ^8.3.4
    '@mantine/modals': ^8.3.4
    '@mantine/notifications': ^8.3.4
    '@mantine/nprogress': ^8.3.4
    '@mantine/spotlight': ^8.3.4
    '@mantine/tiptap': ^8.3.4
  nodejs:
    '@types/node': ^24.7.2
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    typescript: ^5.9.3
  nextjs:
    next: ^15.5.5
    react: ^19.2.0
    react-dom: ^19.2.0
    '@next/bundle-analyzer': ^15.5.5
  tiptap:
    '@tiptap/extension-link': ^3.7.0
    '@tiptap/pm': ^3.7.0
    '@tiptap/react': ^3.7.0
    '@tiptap/starter-kit': ^3.7.0
  postcss:
    postcss: ^8.5.6
    postcss-preset-mantine: ^1.18.0
    postcss-simple-vars: ^7.0.1
    autoprefixer: ^10.4.21
